#1/user sign up
Kaito-a-bit/twitter_clone_app pull request #2
Opened 2022-02-02 02:49 UTC by Kaito-a-bit

○issue
　 #1

2022-02-04 05:50 UTC, Kaito-a-bit commented
○課題
　・ユーザ登録には成功したが成功した時のリダイアレクトURLが呼ばれずに画面遷移できない

2022-02-11 05:08 UTC, Akinori13 commented
gitignoreを後から反映する方法があるので、それを実施してください。
次のprでログイン・ログアウト機能を実装しますが、ご質問の点については[これ](https://docs.djangoproject.com/en/4.0/topics/auth/default/#the-login-required-decorator) が参考になるかと思います。

2022-02-11 14:27 UTC, Kaito-a-bit commented
> gitignoreを後から反映する方法があるので、それを実施してください。

[この記事](https://qiita.com/ytkt/items/a2afd6be8e4f06c1ea25#%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%94%E3%81%A8%E9%80%9D%E3%81%8D%E3%81%9F%E3%81%84%E3%81%A8%E3%81%8D)を参考に`.gitignore`ファイルを編集し、キャッシュを削除しました。

2022-02-15 14:21 UTC, s-nakajima2 requested changes
いくつかレビューしておきました。トップページのデザインが洗練されていて、とても良いと思います。

2022-02-15 14:21 UTC, s-nakajima2 commented on user/templates/user/base.html
> +</html>
`base.html`には、サイトで使う構成要素のブロックとそれを装飾するタグ（あるいは共通で使うような文字）のみが含まれていた方が良いです。[このチュートリアル](https://tutorial.djangogirls.org/ja/template_extending/)のように、
```
# foo/base.html
<h1>
    {% block hoge %}
        1
    {% endblock %}
<\h1>
```
を用意して、
```
# foo/huga.html
{% extends 'foo/base.html' %}
{% block hoge %}
    2
{% endblock %}
```
とすると、`<h1>`タグがなくとも`<h1>`で装飾された2が表示されます。また、`hoge`ブロックについて何も書かなければ`<h1>`で装飾された1が表示されます。これを用意したうえで、`base`を拡張する形でトップページやほかのhtmlファイルを書いてみましょう。

2022-02-15 14:21 UTC, s-nakajima2 commented on user/views.py
> +    template_name = 'user/base.html'
（`base.html`のコメントも参照）`base.html`を拡張して作ったhtmlファイルをトップページにした方が良いでしょう。

2022-02-15 14:21 UTC, s-nakajima2 commented on user/views.py
> +from re import template
```suggestion
```
このモジュールは使われていないので、削除してしまいましょう。

2022-02-15 14:21 UTC, s-nakajima2 commented on .gitignore
> +.DS_STORE
env ディレクトリ、もしくは`*.pyc`に対する.gitignoreが効いていないようです。もう一度gitignoreを試してみてください（前にやっていると思います）。

2022-02-16 02:17 UTC, Kaito-a-bit commented
○修正点　
- 差分に含まれてしまっていた`.pyc`をgit管理の対象から外しました。
- `base.html`を拡張する形でユーザ登録画面・ホーム画面を作り替えました。
尚、上記に加えてログイン画面・ログアウト画面を、`base.html`を拡張する形で実装しようと考えています。
- 上記に伴って不要になった`css`ファイルを削除しました。

2022-02-16 02:31 UTC, s-nakajima2 reviewed
本当に細かいところですが、一つだけコメントしました。

2022-02-16 02:31 UTC, s-nakajima2 commented on user/templates/user/home.html
> +{% extends 'user/base.html'%}
```suggestion
{% extends 'user/base.html' %}
```
細かいところですが、タグの最後にも１スペース入れるようにしましょう。`templates`ディレクトリの中のファイルで、このファイルを含めて他にも同じ修正をする箇所があるので、探してみてください。

2022-02-16 02:36 UTC, Kaito-a-bit commented on user/templates/user/home.html
> +{% extends 'user/base.html'%}
確かに入れないとダメでした！修正しました。

2022-02-16 02:39 UTC, s-nakajima2 reviewed
◎
二次レビューにお渡しします。

2022-02-16 10:58 UTC, Akinori13 requested changes
二点追加してコメントします。
- UserモデルはAbstractBaseUserを拡張し、フィールドを一つ追加してください。
- アカウント登録機能のテストを追加してください。フォームの入力に対して異常系と正常系エラーを作成してください。status_code, リダイレクト先、エラー文、DBで生成されていないかをそれぞれ確認します。

2022-02-16 10:58 UTC, Akinori13 commented on user/templates/user/base.html
> +      {% block second %}
命名をもう少し明瞭にできますか？

2022-02-16 10:58 UTC, Akinori13 commented on user/templates/user/home.html
> +{% block second %}
可読性の観点から、空行をはさんでいただきたいです

2022-02-16 10:58 UTC, Akinori13 commented on user/templates/user/home.html
> +{% load static %}
`base`で読み込み済みなので、消しちゃってください

2022-02-16 10:58 UTC, Akinori13 commented on user/templates/user/sign_up.html
> +        <p>{{ form.password2 }}</p>
errorsとhelp_textを表示するようにしてください。

2022-02-16 10:58 UTC, Akinori13 commented on user/templates/user/top.html
> +  <!-- ↑ログイン画面のURLを入れる -->
このようなときは、`TODO: XXXX`と記入しておくと、検索してタスクのチェックができるのでよいです。そのままでも消しても構いませんので、お任せします。

2022-02-16 10:58 UTC, Akinori13 commented on user/views.py
> +        user = form.save()
[ここ](https://docs.djangoproject.com/en/4.0/topics/auth/default/#django.contrib.auth.authenticate)を参考にauthenticate()を用いてDjangoの認証バックエンドを通してください。

2022-02-19 05:05 UTC, Kaito-a-bit commented
○変更点
- [ ]  ユーザ登録時に`authenticate()`を通すようにした
- [ ] Userのモデルを`AbstractBaseUser`を拡張する形でカスタムのものに変更した
- [ ] フォームに`help_text`, `errors`を表示させるようにした

2022-02-21 11:47 UTC, Kaito-a-bit commented
○TO DO
- [ ] カスタムユーザモデルへの変更
- [ ] ヘルプテキストの表示
- [ ] エラーメッセージの表示
- [ ] Djangoの認証バックエンドへの変更
- [ ] 管理者サイトへのカスタムモデルの適用・表示

2022-02-23 06:57 UTC, Kaito-a-bit commented
デフォルトで`blank=FALSE`, `null=FALSE`らしいので必須フィールドに対する指定を削除した

2022-02-23 09:14 UTC, Akinori13 requested changes
バックアップ機能実装お疲れ様です。いくつか
- 何をインストールしたか分かるようにrequirements.txt作成してください。
- いらないimport文は消しちゃってください
- import文の下に空行を入れることに注意を払いましょう
- migrationファイルは追跡対象にしてください

2022-02-23 09:14 UTC, Akinori13 commented on user/views.py
> +        response = super().form_valid(form) #ここでフォームの情報を保存
実際には`HttpResponseRedirect(self.get_success_url())`が返ります

2022-02-23 09:14 UTC, Akinori13 commented on user/views.py
> +        self.object = user #これは何
[こちらの記事](https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/#django.views.generic.edit.CreateView.object)を確認しましょう。super().form_valid(form)で設定されているのでいりません

2022-02-23 09:14 UTC, Akinori13 commented on user/views.py
> +        password = form.cleaned_data.get('password')
いらないです

2022-02-23 09:14 UTC, Akinori13 commented on user/views.py
> +        user = authenticate(username=username, password=password)
models.pyの`USERNAME_FIELD = "email"`により、username=emailでauthenticateしてください。

2022-02-23 09:14 UTC, Akinori13 commented on user/forms.py
> +class SignUpForm(forms.ModelForm):
現状ではセキュリティ対策が全く行われていない状態ですから、UserCreationFormを使うようにしてください。

2022-02-24 13:45 UTC, Kaito-a-bit commented on twitter_clone_app/settings.py
> +DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
バックアップ用のライブラリの指示に従って、追加しました。
バックアップに使用するストレージを指定しているという認識です。
参考: [Storage settings](https://django-dbbackup.readthedocs.io/en/master/storage.html)

2022-03-01 06:03 UTC, Kaito-a-bit commented on user/forms.py
> +class SignUpForm(forms.ModelForm):
UserCreationFormを使用する形に変更しました。

2022-03-01 06:16 UTC, Kaito-a-bit commented
- `requirements.txt`を作成しました
- 必要のないimportを削除、空行・インデント調整をしました
- migrationsディレクトリ内にある`__pycache__`ファイル以外のものをgit管理の対象に入れました
- `UserCreationForm`を使用してフォームを作成しました
- djangoの認証バックエンドに`email`を用いて通すようにしました

PRが大きくなってすみません😞🙇‍♂️

2022-03-01 10:06 UTC, Akinori13 requested changes
いくつかコメントしました。
加えて仮想環境名をenvではなく、venv等に変更してください。（gitignoreの修正含む）

2022-03-01 10:06 UTC, Akinori13 commented on user/forms.py
> +            'password': 'パスワード'
password1とpassword2は存在しますが、passwordはこのフォームには存在しないのでいりません

2022-03-01 10:06 UTC, Akinori13 commented on user/views.py
> +        username = form.cleaned_data.get('username')
いらないです

2022-03-01 10:06 UTC, Akinori13 commented on user/views.py
> +        login(self.request, self.object)
下記でよいと思います
```suggestion
        login(self.request, user)
```

2022-03-01 10:06 UTC, Akinori13 commented on user/views.py
> +        user = authenticate(username=email)
認証されたuserが存在しなかった場合はエラーを返してあげましょう

2022-03-02 03:45 UTC, Akinori13 commented on user/forms.py
> +        fields = ('username', 'email', 'birthday', 'password1')
①
指定する必要はないと思います。

②
継承元では、
```
fields = ("username",)
```
継承後にusernameを入れないと、usernameが抜かれた状態で上書きされてしまうということです

2022-03-05 02:14 UTC, Akinori13 requested changes
いらないImportを削除してください。
これほどファイル数が大きくなっているのは、masterブランチ自体に仮想環境等が含まれていたからでしょう。ご提案通り、テスト機能をこのPRから分離します。

2022-03-05 02:14 UTC, Akinori13 commented on user/views.py
> +            return form.add_error("ユーザが存在しません。")
403がよいと思います。

2022-03-07 03:28 UTC, Kaito-a-bit commented on user/views.py
> +            return form.add_error("ユーザが存在しません。")
403(`permissonDenied`)を返す処理を記述しました。ユーザ登録を試行した所、常に403エラーが返ってきてしまいます。このエラーが返ってくるということは**Emailでの認証が機能していないから**ということが推測できますが、何故この処理を通過しないのかがわからないです。emailを用いた`authenticate()`が機能していなかったからかと思い、
以下の記事を参考にemailを用いてauthenticate()をオーバーライドしたものを作成しましたが、変わらず403エラーが返ってきてしまいます。何かヒントを頂けると幸いです。

2022-03-07 23:36 UTC, Kaito-a-bit commented
`check_password`が定義されていない

2022-03-08 00:29 UTC, Kaito-a-bit commented on user/views.py
> +        user = authenticate(username=email)
ここの認証が通りません。
`email`を`username`として認証バックエンドに通す方法を調べましたが、どの記事を参考にしても
**前提としてユーザーネームのカラムを持たないカスタムモデルを作成してUSERNAME_FIELDをemailとする**という方法のものでした。前提としてユーザネームを持つという要件の確認と、要件としてユーザーネームのカラムも持つ必要があると思うのですが、ユーザーネームを登録させつつ、emailで認証を通す方法があれば教えて頂きたいです。

2022-03-08 06:07 UTC, Akinori13 commented on user/views.py
> +        user = authenticate(username=email)
こちらで確認してください
```
user = authenticate(username=email, password=password)
```

2022-03-08 07:00 UTC, Kaito-a-bit commented
user = authenticate(username=email, password=password)で既に試行していたが、`password`の取得ができていなかった。

2022-03-13 03:51 UTC, Kaito-a-bit commented
- フォームの入力に対して異常系と正常系エラーを作成してください。
status_code, リダイレクト先、エラー文、DBで生成されていないかをそれぞれ確認￥。

2022-03-14 07:06 UTC, Kaito-a-bit commented
テスト作成の参考記事
- [Djangoでテストを書こう【前編】](https://selfs-ryo.com/detail/django_test_1#_1)
- [はじめての Django アプリ作成、その 5](https://docs.djangoproject.com/ja/4.0/intro/tutorial05/)
- [テストツール](https://docs.djangoproject.com/ja/4.0/topics/testing/tools/)

2022-03-14 08:48 UTC, Kaito-a-bit commented
- 各ページ（`top`, `signup`, `home`）のステータスコードを確認するテストを作成
- 短すぎるパスワードを弾くテストを作成
- 長すぎるユーザネームを弾くテストを作成

2022-03-15 02:46 UTC, Kaito-a-bit commented
○リダイレクト先のテスト
リダイレクト先の検証については下記のサイトを参考に作成した。
- [【Django】テストでリダイレクト先のページを検証する方法](https://qiita.com/kozakura16/items/c08b8cb8da12ace78658)
- [Django testing how to assert Redirect
](https://stackoverflow.com/questions/47020253/django-testing-how-to-assert-redirect)

```Python 
def test_redirect_to_home(self):
    data = {
      'username': 'Gym Motivation3',
      'email': 'nanaMotive@gmail.com',
      'birthday': '2002-1-1',
      'password1': 'kjhd1245',
      'password2': 'kjhd1245',
    }
    self.response = self.client.post('/signup/', data)
    self.assertRedirects(self.response, '/home/', status_code=302, target_status_code=200, msg_prefix='', fetch_redirect_response=True)
```

上記のテストの実行結果は以下の通りとなった。
以下の結果を**`302`が返ってくるはずだけど`200`が返ってきた。**という趣旨のエラーだと解釈した。
<img width="979" alt="スクリーンショット 2022-03-15 11 44 47" src="https://user-images.githubusercontent.com/73689418/158295574-e5a2ccde-3b8f-46fd-a90b-3967fdf1aa42.png">

2022-03-16 09:26 UTC, fumiharun11 commented
サインアップ処理自体に失敗しているため生じているエラーです。
以下のコメント箇所が原因と考えられます。
```py
def test_redirect_to_home(self):
    data = {
      'username': 'Gym Motivation3', # 半角スペースがある
      'email': 'nanaMotive@gmail.com',
      'birthday': '2002-1-1',
      'password1': 'kjhd1245',
      'password2': 'kjhd1245',
    }
    self.response = self.client.post('/signup/', data)
    self.assertRedirects(self.response, '/home/', status_code=302, target_status_code=200, msg_prefix='', fetch_redirect_response=True)
```

2022-03-16 10:19 UTC, fumiharun11 commented on user/models.py
> +        if extra_fields.get('is_staff') is not True:
上で`True`に設定する処理が存在するので内部でバリデーションする意味はあるかな？

2022-03-16 10:19 UTC, fumiharun11 commented on user/models.py
> +        if extra_fields.get('is_superuser') is not True:
同上

2022-03-16 10:19 UTC, fumiharun11 commented on user/tests.py
> +  def testStatus(self):
ファイル全体でインデントが他のファイルと異なるのは何故ですか？

2022-03-16 10:19 UTC, fumiharun11 commented on user/tests.py
> +    self.assertRedirects(self.response, '/home/', status_code=302, target_status_code=200, msg_prefix='', fetch_redirect_response=True)
デフォルト引数が与えられている箇所で値を変更しない場合は省略しても大丈夫です

2022-03-16 10:19 UTC, fumiharun11 commented on user/tests.py
> +  def test_not_unique_email(self):
テスト内容に対してメソッド名は適切ですか？
通常の成功処理として認識しています

2022-03-16 10:19 UTC, fumiharun11 commented on user/tests.py
> +class RegisterErrorTests(TestCase):
`SignUpViewErrorTests`として命名に規則性を持たせるか、`SignUpViewTests`に統合するようにしてください。

2022-03-16 10:19 UTC, fumiharun11 commented on user/tests.py
> +  def testStatus(self):
キャメルケースの記法でもテストは正常に実施されていましたか？

2022-03-16 10:19 UTC, fumiharun11 commented on user/tests.py
> +  def test_too_short_password(self):
失敗処理系でデータの作成が目的であったものはデータが作成されていないことをテストしてください。

2022-03-17 05:24 UTC, Kaito-a-bit commented on user/models.py
> +        if extra_fields.get('is_staff') is not True:
不要なバリデーションを削除しました。

2022-03-17 05:24 UTC, Kaito-a-bit commented on user/tests.py
> +  def testStatus(self):
インデントをスペース4つに統一しました。

2022-03-17 05:25 UTC, Kaito-a-bit commented on user/tests.py
> +    self.assertRedirects(self.response, '/home/', status_code=302, target_status_code=200, msg_prefix='', fetch_redirect_response=True)
不要な引数を削除しました。

2022-03-17 05:27 UTC, Kaito-a-bit commented on user/tests.py
> +  def test_not_unique_email(self):
テストの命名を変更しました。アカウント作成のテストの為`test_user_creation`としました。

2022-03-17 05:29 UTC, Kaito-a-bit commented on user/tests.py
> +  def testStatus(self):
実施されましたが、キャメルケースに命名規則を統一しました。

2022-03-17 05:29 UTC, Kaito-a-bit commented on user/tests.py
> +class RegisterErrorTests(TestCase):
`SignUpViewErrorTests`という命名に変更しました。

2022-03-17 05:40 UTC, Kaito-a-bit commented on user/tests.py
> +  def test_too_short_password(self):
失敗系処理テスト内において、失敗要因でフィルターをかけてオブジェクトが存在しないことを確かめる形に修正しました。

2022-03-17 09:24 UTC, fumiharun11 reviewed
テストケースメソッドのメソッド命名については全体的に参考にしてみてください。

2022-03-17 09:24 UTC, fumiharun11 commented on requirements.txt
> +asgiref==3.4.1
`Django`と`django-dbbackup`以外のパッケージはそれぞれ何に用いるためにインストールする想定ですか？

2022-03-17 09:24 UTC, fumiharun11 commented on user/admin.py
> +admin.site.register(User)
`UserAdmin`を定義していてregisterに含めていないのはなぜですか？

2022-03-17 09:24 UTC, fumiharun11 commented on user/admin.py
> +class UserAdmin(admin.ModelAdmin):
何のために定義していますか？

2022-03-17 09:24 UTC, fumiharun11 commented on user/admin.py
> +from django.utils.translation import ugettext_lazy as _
不要なパッケージはimportせず必要になった際に記述してimportするようにしましょう。

2022-03-17 09:24 UTC, fumiharun11 commented on user/forms.py
> +            'email': 'email',
細かい質問ですが、以下のようにしていないのは意図的ですか？
```suggestion
            'email': 'メールアドレス',            
```

2022-03-17 09:24 UTC, fumiharun11 commented on user/tests.py
> +class TopViewTests(TestCase):
実装側では`BaseView`なのでどちらかに合わせて統一すると良いと思います。
IMO: View定義の方を`Top`にすることを提案します

2022-03-17 09:24 UTC, fumiharun11 commented on user/tests.py
> +from urllib import response
これは何のためにimportしていますか？

2022-03-17 09:24 UTC, fumiharun11 commented on user/tests.py
> +from django.test import TestCase, Client
`Client`は何のためにimportしていますか？

2022-03-17 09:24 UTC, fumiharun11 commented on user/tests.py
> +from django.utils import timezone
同上

2022-03-17 09:24 UTC, fumiharun11 commented on user/tests.py
> +        self.response = self.client.get('/')
view関数に対応させている名前から`reverse()`で取得する方針と直接エンドポイントを指定(`'/'`)する方針が混在しているのでどちらかに統一されていると良いと思いました

2022-03-17 09:24 UTC, fumiharun11 commented on user/tests.py
> +    def test_status(self):
命名について
`test_status`がアクセス成功時のステータスを指すのか失敗時のステータスを指すのか名前から判断出来るとより良くなると考えています。
リクエストメソッドも含めて`test_get_success`といったように命名することでGETリクエスト成功時を表現することが出来るので参考にしてください。
例.
- xxxによる原因でGET失敗時: `test_get_failed_xxx`
- フォームのyyy未記入による原因でPOST失敗時: `test_post_failed_empty_yyy`

2022-03-17 09:24 UTC, fumiharun11 commented on user/views.py
> +        if user is not None:
サインアップ成功を前提とした処理でこのケースに該当しないパターンはどういう時が考えられますか？

2022-03-17 09:38 UTC, Kaito-a-bit commented on user/admin.py
> +class UserAdmin(admin.ModelAdmin):
カスタムモデルへの変更で作成途中になっていました。削除します。

2022-03-17 09:38 UTC, Kaito-a-bit commented on user/admin.py
> +admin.site.register(User)
[comment](https://github.com/Kaito-a-bit/twitter_clone_app/pull/2#discussion_r828925655)に同じです。

2022-03-17 09:39 UTC, Kaito-a-bit commented on user/admin.py
> +from django.utils.translation import ugettext_lazy as _
削除しました。

2022-03-17 09:47 UTC, Kaito-a-bit commented on user/tests.py
> +class TopViewTests(TestCase):
`View`の方を`TopView`に変更しました。

2022-03-17 09:48 UTC, Kaito-a-bit commented on user/tests.py
> +from urllib import response
不要な為削除しました。

2022-03-17 09:48 UTC, Kaito-a-bit commented on user/tests.py
> +from django.test import TestCase, Client
同様に不要なため削除しました。

2022-03-17 09:52 UTC, Kaito-a-bit commented on user/tests.py
> +        self.response = self.client.get('/')
`reverse`を用いる形に変更しました。

2022-03-17 10:00 UTC, Kaito-a-bit commented on user/tests.py
> +    def test_status(self):
ステータスコードをテストする関数についてテスト名を変更しました。

2022-03-20 11:52 UTC, fumiharun11 approved these changes
LGTM

2022-03-21 01:04 UTC, merged